version: '2'

services:

  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ./www:/var/www/html
    expose:
      - "9000"
    depends_on:
      - mysql

  nginx:
    build:
      context: ./nginx
    volumes:
      - ./www:/var/www/html
      - ./nginx/log:/var/log/nginx
    ports:
      - "8000:80"
    depends_on:
      - php-fpm

  mysql:
    image: mysql:5.6
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    links:
      - mysql:db

volumes:
  mysql-data: